fix: bundles are stored in job_history in their original format
aws-deadline/deadline-cloud pull request #344
Opened 2024-06-07 14:53 UTC by crowecawcaw

### What was the problem/requirement? (What/Why)
The bundle GUI submitter does not always save asset references or parameter values in the original file format when the bundle is saved to the `job_history` directory.

Job bundles have data files for the template, asset references and parameter values, and these files can be either JSON or YAML. If input job bundle has a JSON template, the saved bundle's template will also by JSON, but the asset references and parameter values will still be saved as YAML.

### What was the solution? (How)
Update the bundle saving logic so to that asset references and parameter values are saved in the same format as the job template.

### What is the impact of this change?
This unblocks some other work I'm doing on the Keyshot submitter where Keyshot's Python interpreter can only read and write JSON files. If saved bundle data is all in JSON, the submitter will be able to load it to find previously selected settings.

### How was this change tested?
I created a bundle with a JSON template, opened it with the GUI submitter, changed some parameters and job attachments, then exported the bundle. I verified that the new bundle in `job_history` had all JSON files. I also opened the GUI submitter for the new template and verified it loaded the JSON references and parameters correctly.

### Was this change documented?
No - bug fix.

### Is this a breaking change?
No

----

*By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.*

2024-06-07 21:03 UTC, epmog requested changes
Code looks good, just need to ensure it's in the right home! Thanks Stephen

2024-06-07 21:03 UTC, epmog commented on src/deadline/client/job_bundle/loader.py
> +    with open(
Missing a docstring (and it's public!), we should include something here

2024-06-07 21:03 UTC, epmog commented on src/deadline/client/job_bundle/loader.py
> +def save_yaml_or_json_to_file(
Should this be moved to a different module? It's currently under `loader` where everything reads in content. feels like we may need to move it to somewhere like `deadline_yaml_dump` for writing out content. Should its naming be similar, like `yaml_or_json_dump`? Not certain myself. Thoughts?

2024-06-10 15:15 UTC, crowecawcaw commented on src/deadline/client/job_bundle/loader.py
> +def save_yaml_or_json_to_file(
Moved!

2024-06-11 15:06 UTC, lucaseck approved these changes, later dismissed

2024-06-18 14:51 UTC, epmog approved these changes

2024-06-18 15:27 UTC, lucaseck approved these changes

2024-06-18 23:46 UTC, merged