fix: Skip creating GUI components for parameters without types
aws-deadline/deadline-cloud pull request #360
Opened 2024-06-20 19:24 UTC by evanspearman-a

### What was the problem/requirement? (What/Why)

The bundle submitter GUI will fail to open a job bundle if a parameter has a value in `parameter_values` but the parameter does not exist in the template.

### What was the solution? (How)

The error was caused when trying to generate a GUI component for the parameter. `parameter_values` does not contain type information for the parameter, only the value. The code that generates a component for a parameter assumes there is type information for all parameters. If type information is not found, we simply skip generating a component for that parameter. Note that we still want to retain these parameter values as they can still be used to populate queue parameter values.

### What is the impact of this change?

Job bundles as described above can now be opened in the bundle submission GUI. In particular, job bundles generated by the integrated submitters when queue environment parameters were present will now work with the job bundle submission GUI.

### How was this change tested?

I opened a job bundle that was previously not opening.

### Was this change documented?

No

### Is this a breaking change?

No

----

*By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.*

2024-06-20 20:17 UTC, jusiskin requested changes
Looks good, but can we please rename the PR and commit title as it should appear in the release notes?

2024-06-20 20:22 UTC, jusiskin approved these changes

2024-06-21 12:54 UTC, crowecawcaw commented
You mentioned that you can now open bundles with queue parameters, but can you also submit them?

2024-06-21 12:54 UTC, crowecawcaw approved these changes

2024-06-21 12:54 UTC, crowecawcaw commented
This would be better with a unit test.

2024-06-21 14:39 UTC, evanspearman-a commented
> You mentioned that you can now open bundles with queue parameters, but can you also submit them?

Yes

> This would be better with a unit test.

This change is in the UI code. This project isn't set up for unit tests involving UI code. I looked into it, but there are some things that would need to be figured out with respect to Qt bindings in order to get that to work. Given that this is a fairly trivial change, I don't think it's worth figuring that out to test this particular change.

2024-06-21 14:46 UTC, merged