feat: support skipping prompts for installing GUI dependencies
aws-deadline/deadline-cloud pull request #395
Opened 2024-07-05 22:10 UTC by crowecawcaw

### What was the problem/requirement? (What/Why)
DCM should be able to invoke `deadline bundle gui-submit` non-CLI users can still submit bundles. But if the GUI dependencies aren't already installed, the command will hang until the prompt about installing GUI dependencies is answered.

### What was the solution? (How)
Support a `-y` flag that skips the prompt.

### What is the impact of this change?
DCM can invoke the bundle submitter more reliably.

### How was this change tested?
By uninstalling PySide and then calling `deadline bundle gui-submit` and `deadline config gui` with and without the `-y` flag.

### Was this change documented?
Yes - in the CLI help.

### Is this a breaking change?
No

----

*By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.*

2024-07-05 23:10 UTC, epmog requested changes
We have some lessons learned with the regular `submit` command that a `--yes`/`-y` for these bigger workflows that can have multiple prompts does not work well. It's not obvious what the `--yes` should be choosing if a default is not affirmative. It begins to become arbitrary and you lose fine-grained control.

After the first-use, the -y isn't even used for anything since the user won't be prompted again.

Instead, what are your thoughts about doing something like `--ensure-gui`? This way we can still bypass this by choosing ahead of time without confusing it with other prompts/options

2024-07-11 15:11 UTC, lucaseck approved these changes

2024-07-11 21:22 UTC, epmog commented on src/deadline/client/ui/__init__.py
> +def gui_context_for_cli(automatically_install_dependencies: bool):
Should this have a default value of False? I know the flags we pass in have a default value of False, but adding that here would assist in some safety of a new CLI being added that uses the gui but does not provide this CLI arg.

2024-07-11 21:23 UTC, epmog approved these changes

2024-07-11 21:52 UTC, merged