test: add tests for submitter input validation
aws-deadline/deadline-cloud pull request #534
Opened 2024-12-12 07:16 UTC by AuxinJeron

Fixes: N/A

### What was the problem/requirement? (What/Why)

There is no test to verify the input of the submitter has been validated

### What was the solution? (How)

Use the Qt pytest to verify the input in the submitter has been validator

### What is the impact of this change?

Submitter input will be verified to be validated 

### How was this change tested?

See [DEVELOPMENT.md](https://github.com/aws-deadline/deadline-cloud/blob/mainline/DEVELOPMENT.md#testing) for information on running tests.

- Have you run the unit tests? Yes
- Have you run the integration tests? No
- Have you made changes to the `download` or `asset_sync` modules? If so, then it is highly recommended
  that you ensure that the docker-based unit tests pass. No

### Was this change documented?

- Are relevant docstrings in the code base updated? No
- Has the README.md been updated? If you modified CLI arguments, for instance. No

### Does this PR introduce new dependencies?

This library is designed to be integrated into third-party applications that have bespoke and customized deployment environments. Adding dependencies will increase the chance of library version conflicts and incompatabilities. Please evaluate the addition of new dependencies. See the [Dependencies](https://github.com/aws-deadline/deadline-cloud/blob/mainline/DEVELOPMENT.md#dependencies) section of DEVELOPMENT.md for more details.

*   [ ] This PR adds one or more new dependency Python packages. I acknowledge I have reviewed the considerations for adding dependencies in [DEVELOPMENT.md](https://github.com/aws-deadline/deadline-cloud/blob/mainline/DEVELOPMENT.md#dependencies).
*   [X] This PR does not add any new dependencies.

### Is this a breaking change?

A breaking change is one that modifies a public contract in a way that is not backwards compatible. See the 
[Public Contracts](https://github.com/aws-deadline/deadline-cloud/blob/mainline/DEVELOPMENT.md#public-contracts) section
of the DEVELOPMENT.md for more information on the public contracts.

If so, then please describe the changes that users of this package must make to update their scripts, or Python applications.

This change ins not a breaking change.

### Does this change impact security?

- Does the change need to be threat modeled? For example, does it create or modify files/directories that must only be readable by the process owner?
    - If so, then please label this pull request with the "security" label. We'll work with you to analyze the threats.

----

This change does not impact security

*By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.*

2024-12-13 06:29 UTC, AuxinJeron commented on .github/workflows/code_quality.yml
> +    uses: AuxinJeron/.aws-deadline-github/.github/workflows/reusable_python_build.yml@ubuntu-pre-steps
This will be updated while https://github.com/aws-deadline/.github/pull/24 has been approved

2024-12-13 15:36 UTC, moorec-aws requested changes
We need documentation changes for the package installation if this change is going to impact development workflow for testing.

2024-12-13 17:43 UTC, crowecawcaw submitted a review, later dismissed

2024-12-13 19:20 UTC, epmog commented on requirements-testing.txt
> +PySide6-essentials == 6.7.1; python_version > '3.8'
Should we not have a range of supported versions for testing as well? We can probably just do `>= 6.6.*`

2024-12-13 22:38 UTC, leon-li-inspire commented on requirements-testing.txt
> +PySide6-essentials == 6.7.1; python_version > '3.8'
I hardcoded the supported version since there is one syntax error for QtGui.pyi which affected several versions in the range.https://bugreports.qt.io/browse/PYSIDE-2665

I tried to use the range before, but the test failed like mentioned in https://stackoverflow.com/questions/78345753/mypy-checking-pyi-in-venv-despite-excluding-it

2024-12-14 01:03 UTC, AuxinJeron commented
Added the notes in the uni tests section of development document

2024-12-17 17:59 UTC, moorec-aws approved these changes

2024-12-17 18:23 UTC, crowecawcaw approved these changes

2024-12-17 18:43 UTC, merged